name: lorien_chat_list
description: "LORIEN.DEV Chat list."
version: 0.0.1
homepage: https://github.com/lorien-dev/chat_list

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
